FROM nginx:stable-alpine

COPY deploy/fly/nginx.conf /etc/nginx/conf.d/default.conf
COPY app/web/static/index.html /usr/share/nginx/html/index.html
COPY app/web/static/assets /usr/share/nginx/html/assets
COPY deploy/fly/search.html /usr/share/nginx/html/search.html

EXPOSE 8080
